### ISSUE TITLE
Questions for contributing

### ISSUE THREAD

**Issue by code-chris** [Prior99/fints#3]
Hi,

first off, thanks for developing this awesome fints-library! It's the first client which just works out of the box without hacking around and finding hidden flags and requirements...

I implemented the **HKSAL** and corresponding **HISAL** event successfully. But now I have some questions before I can submit this as PR.

1. In the segment unit-tests and the fixtures for the client-tests there are several raw protocol strings. Where do they come from? Are they generated or manually constructed? If last one, is there a good specification for the structure of those messages?
2. Are there any special naming conventions for public accessible property names (e.g. return values)?

Thanks!

**Comment by Prior99** [comment]
Hi, 

thanks for your kind words. I would be happy to accept any contribution. 

**About the mock strings**

I generated those strings by using fints with my own real banking account, anonymizing the data afterwards. There is also [this javascript implementation](https://www.npmjs.com/package/open-fin-ts-js-client) which offers a mock server for testing purposes. I actually read through [the official documentation](https://www.hbci-zka.de/spec/3_0.htm) in order to understand the basic protocol. It also features a lot of examples. Additionally, [this python implementation] (https://github.com/raphaelm/python-fints) is well-written and I used it as a reference implementation.

**About coding guidelines**

A linter is in place, enforcing basic conventions. There are no conventions for method names and properties. I tried to keep them short, concise and descriptive.
